### ISSUE TITLE
No need to wait after Wire.requestFrom() and it should not be followed by Wire.endTransmission().

### ISSUE THREAD

**Issue by Koepel** [scottburch/boat-systems#1]
The usage of the Wire library is not okay in these files:
- boat-systems/hardware/compassAndRudderInterface/firmware/autopilot/libraries/LIS3MDL/LIS3MDL.cpp
- boat-systems/hardware/compassAndRudderInterface/firmware/autopilot/libraries/LSM6/LSM6.cpp
- boat-systems/hardware/compassAndRudderInterface/firmware/autopilot/libraries/L3G/L3G.cpp
- boat-systems/hardware/compassAndRudderInterface/firmware/autopilot/libraries/LSM303/LSM303.cpp

There is no such thing as a timeout after a Wire.requestFrom(). 
The Wire.requestFrom() should not be followed by Wire.endTransmission.
Explanation: [Common-mistakes](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes), number 1 and 2.
See also my [alternative explanation of the functions of the Wire library](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Explanation-of-the-functions-of-the-Wire-library).

**Comment by scottburch** [comment]
Thanks for the comment.   Those are not my libraries, but I will check if there are newer versions.

**Comment by scottburch** [comment]
Closing

**Comment by Koepel** [comment]
Is Pololu the original author of the code? I wanted to create a issue over there, but I already did: https://github.com/pololu/zumo-shield-arduino-library/issues/1

**Comment by scottburch** [comment]
@Koepel I don't remember where I got those files from.  It has been a couple of years.  But, it probably was them.  Thanks again.
